FlySite.create(name: 'big_sur'.split('_').map(&:capitalize).join(' '),
  slug: 'big_sur',
  lat: 35.971,
  lng: -121.453,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 8,
  speedmin_edge: 0,
  speedmax_edge: 11,
  dir_ideal: ['SW', 'WSW', 'W'],
  dir_edge: ['SSW', 'SW', 'WSW', 'W', 'WNW'])

FlySite.create(name: 'berkeley'.split('_').map(&:capitalize).join(' '),
  slug: 'berkeley',
  lat: 37.871,
  lng: -122.319,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 7,
  speedmax_ideal: 10,
  speedmin_edge: 6,
  speedmax_edge: 11,
  dir_ideal: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'],
  dir_edge: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'blue_rock'.split('_').map(&:capitalize).join(' '),
  slug: 'blue_rock',
  lat: 38.140,
  lng: -122.217,
  hourstart: 15,
  hourend: 19,
  speedmin_ideal: 8,
  speedmax_ideal: 10,
  speedmin_edge: 7,
  speedmax_edge: 13,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'channing'.split('_').map(&:capitalize).join(' '),
  slug: 'channing',
  lat: 38.098,
  lng: -122.180,
  hourstart: 12,
  hourend: 19,
  speedmin_ideal: 8,
  speedmax_ideal: 10,
  speedmin_edge: 7,
  speedmax_edge: 12,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'channing_east'.split('_').map(&:capitalize).join(' '),
  slug: 'channing_east',
  lat: 38.099,
  lng: -122.180,
  hourstart: 12,
  hourend: 19,
  speedmin_ideal: 7,
  speedmax_ideal: 9,
  speedmin_edge: 5,
  speedmax_edge: 12,
  dir_ideal: ['ENE', 'E', 'ESE'],
  dir_edge: ['NE', 'ENE', 'E', 'ESE', 'SE'])

FlySite.create(name: 'coloma'.split('_').map(&:capitalize).join(' '),
  slug: 'coloma',
  lat: 38.822,
  lng: -120.889,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 8,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'davis'.split('_').map(&:capitalize).join(' '),
  slug: 'davis',
  lat: 38.570,
  lng: -121.820,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 7,
  speedmax_ideal: 10,
  speedmin_edge: 6,
  speedmax_edge: 12,
  dir_ideal: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'],
  dir_edge: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'diablo_juniper'.split('_').map(&:capitalize).join(' '),
  slug: 'diablo_juniper',
  lat: 37.881,
  lng: -121.914,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['SW', 'WSW'],
  dir_edge: ['SW', 'WSW', 'W'])

FlySite.create(name: 'diablo_towers'.split('_').map(&:capitalize).join(' '),
  slug: 'diablo_towers',
  lat: 37.881,
  lng: -121.914,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 3,
  speedmax_ideal: 7,
  speedmin_edge: 3,
  speedmax_edge: 10,
  dir_ideal: ['WNW', 'NW'],
  dir_edge: ['W', 'WNW', 'W', 'NW', 'NNW'])

FlySite.create(name: 'day_dreams'.split('_').map(&:capitalize).join(' '),
  slug: 'day_dreams',
  lat: 39.242,
  lng: -120.008,
  hourstart: 12,
  hourend: 18,
  speedmin_ideal: 5,
  speedmax_ideal: 9,
  speedmin_edge: 5,
  speedmax_edge: 12,
  dir_ideal: ['SSW', 'SW', 'WSW'],
  dir_edge: ['S', 'SSW', 'SW', 'WSW', 'W'])

FlySite.create(name: 'drakes'.split('_').map(&:capitalize).join(' '),
  slug: 'drakes',
  lat: 38.026,
  lng: -122.965,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 8,
  speedmax_ideal: 12,
  speedmin_edge: 7,
  speedmax_edge: 18,
  dir_ideal: ['SE', 'SSE'],
  dir_edge: ['ESE', 'SE', 'SSE', 'S'])

FlySite.create(name: 'dunlap'.split('_').map(&:capitalize).join(' '),
  slug: 'dunlap',
  lat: 36.765,
  lng: -119.098,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 11,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])
  
FlySite.create(name: 'duck_hill'.split('_').map(&:capitalize).join(' '),
  slug: 'duck_hill',
  lat: 39.241,
  lng: -119.741,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['SW','WSW', 'W', 'WNW', 'NW'],
  dir_edge: ['WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'ed_levin'.split('_').map(&:capitalize).join(' '),
  slug: 'ed_levin',
  lat: 37.475,
  lng: -121.861,
  hourstart: 9,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 8,
  speedmin_edge: 0,
  speedmax_edge: 13,
  dir_ideal: ['SSE', 'S', 'SSW', 'SW', 'WSW', 'W'],
  dir_edge: ['SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'elk_mountain'.split('_').map(&:capitalize).join(' '),
  slug: 'elk_mountain',
  lat: 39.277,
  lng: -122.941,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 9,
  dir_ideal: ['ESE','SE','SSE','NW', 'WNW'],
  dir_edge: ['ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WNW', 'NW'])

FlySite.create(name: 'goat'.split('_').map(&:capitalize).join(' '),
  slug: 'goat',
  lat: 38.443,
  lng: -123.122,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 9,
  speedmax_ideal: 13,
  speedmin_edge: 8,
  speedmax_edge: 15,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'hat_creek'.split('_').map(&:capitalize).join(' '),
  slug: 'hat_creek',
  lat: 40.842,
  lng: -121.428,
  hourstart: 15,
  hourend: 19,
  speedmin_ideal: 5,
  speedmax_ideal: 9,
  speedmin_edge: 3,
  speedmax_edge: 12,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW'])

FlySite.create(name: 'hull'.split('_').map(&:capitalize).join(' '),
  slug: 'hull',
  lat: 39.509,
  lng: -122.937,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 8,
  dir_ideal: ['SSW', 'SW', 'WSW'],
  dir_edge: ['S', 'SSW', 'SW', 'WSW', 'W'])

FlySite.create(name: 'indian_valley'.split('_').map(&:capitalize).join(' '),
  slug: 'indian_valley',
  lat: 40.194,
  lng: -120.923,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 3,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 9,
  dir_ideal: ['SSW', 'SW', 'WSW'],
  dir_edge: ['S', 'SSW', 'SW', 'WSW', 'W'])

FlySite.create(name: 'lakeview_blackcap'.split('_').map(&:capitalize).join(' '),
  slug: 'lakeview_blackcap',
  lat: 42.204264,
  lng: -120.330122,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['WSW', 'W'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'lakeview_dohertyslide'.split('_').map(&:capitalize).join(' '),
  slug: 'lakeview_dohertyslslide',
  lat: 42.019267,
  lng: -119.485666,
  hourstart: 16,
  hourend: 19,
  speedmin_ideal: 4,
  speedmax_ideal: 7,
  speedmin_edge: 3,
  speedmax_edge: 10,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['WSW', 'W', 'WNW'])

FlySite.create(name: 'lakeview_sugarhill'.split('_').map(&:capitalize).join(' '),
  slug: 'lakeview_sugarhill',
  lat: 41.806527,
  lng: -120.328704,
  hourstart: 10,
  hourend: 19,
  speedmin_ideal: 2,
  speedmax_ideal: 7,
  speedmin_edge: 3,
  speedmax_edge: 8 ,
  dir_ideal: ['WSW', 'SW'],
  dir_edge: ['WSW', 'W', 'SW'])

FlySite.create(name: 'lakeview_hadleybutte'.split('_').map(&:capitalize).join(' '),
  slug: 'lakeview_hadleybutte',
  lat: 42.690833,
  lng: -120.666117,
  hourstart: 10,
  hourend: 19,
  speedmin_ideal: 2,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 9 ,
  dir_ideal: ['N', 'NNE', 'NNW'],
  dir_edge: ['N', 'NNE', 'NE', 'NW', 'NNW'])

FlySite.create(name: 'lagoon_kite'.split('_').map(&:capitalize).join(' '),
  slug: 'lagoon_kite',
  lat: 38.333,
  lng: -122.002,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 7,
  speedmax_ideal: 11,
  speedmin_edge: 6,
  speedmax_edge: 13,
  dir_ideal: ['S', 'SSW','SW', 'WSW', 'W', 'WNW','NW', 'NNW'],
  dir_edge: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'lagoon'.split('_').map(&:capitalize).join(' '),
  slug: 'lagoon',
  lat: 38.333,
  lng: -122.002,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 7,
  speedmax_ideal: 11,
  speedmin_edge: 6,
  speedmax_edge: 13,
  dir_ideal: ['SW', 'WSW', 'W', 'WNW'],
  dir_edge: ['SSW', 'SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'mussel_rock'.split('_').map(&:capitalize).join(' '),
  slug: 'mussel_rock',
  lat: 37.674,
  lng: -122.495,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 9,
  speedmax_ideal: 14,
  speedmin_edge: 8,
  speedmax_edge: 20,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'mount_tam'.split('_').map(&:capitalize).join(' '),
  slug: 'mount_tam',
  lat: 37.911,
  lng: -122.625,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 8,
  speedmin_edge: 0,
  speedmax_edge: 12,
  dir_ideal: ['S', 'SSW', 'SW', 'WSW', 'W'],
  dir_edge: ['SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW'])

FlySite.create(name: 'mission'.split('_').map(&:capitalize).join(' '),
  slug: 'mission',
  lat: 37.518,
  lng: -121.892,
  hourstart: 9,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 8,
  speedmin_edge: 0,
  speedmax_edge: 12,
  dir_ideal: ['SW', 'WSW', 'W', 'WNW', 'NW'],
  dir_edge: ['SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'N'])

FlySite.create(name: 'owens_lee'.split('_').map(&:capitalize).join(' '),
  slug: 'owens_lee',
  lat: 37.9763,
  lng: -119.1680,
  hourstart: 9,
  hourend: 13,
  speedmin_ideal: 0,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 8 ,
  dir_ideal: ['E', 'ENE'],
  dir_edge: ['NE', 'ENE', 'E', 'ESE', 'SE'])

FlySite.create(name: 'oroville'.split('_').map(&:capitalize).join(' '),
  slug: 'oroville',
  lat: 39.537,
  lng: -121.628,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 7,
  speedmax_ideal: 10,
  speedmin_edge: 6,
  speedmax_edge: 12,
  dir_ideal: ['N', 'NNW'],
  dir_edge: ['N', 'NNE', 'NNW'])

FlySite.create(name: 'pine'.split('_').map(&:capitalize).join(' '),
  slug: 'pine',
  lat: 43.819367,
  lng: -120.932833,
  hourstart: 10,
  hourend: 19,
  speedmin_ideal: 2,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 9 ,
  dir_ideal: ['W', 'WNW', 'NW'],
  dir_edge: ['WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'potato_hill'.split('_').map(&:capitalize).join(' '),
  slug: 'potato_hill',
  lat: 39.3317,
  lng: -122.685,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 5,
  speedmin_edge: 0,
  speedmax_edge: 8,
  dir_ideal: ['ENE', 'E'],
  dir_edge: ['NE', 'ENE', 'E', 'ESE', 'SE'])

FlySite.create(name: 'sand_city'.split('_').map(&:capitalize).join(' '),
  slug: 'sand_city',
  lat: 36.626,
  lng: -121.844,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 9,
  speedmax_ideal: 13,
  speedmin_edge: 7,
  speedmax_edge: 18,
  dir_ideal: ['WSW', 'W','WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'shasta'.split('_').map(&:capitalize).join(' '),
  slug: 'shasta',
  lat: 41.377,
  lng: -122.195,
  hourstart: 7,
  hourend: 12,
  speedmin_ideal: 0,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 9 ,
  dir_ideal: ['SSW', 'SW', 'WSW'],
  dir_edge: ['S', 'SSW', 'SW', 'WSW', 'W'])

FlySite.create(name: 'shoreline'.split('_').map(&:capitalize).join(' '),
  slug: 'shoreline',
  lat: 37.430,
  lng: -122.076,
  hourstart: 9,
  hourend: 19,
  speedmin_ideal: 7,
  speedmax_ideal: 11,
  speedmin_edge: 5,
  speedmax_edge: 13,
  dir_ideal: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'],
  dir_edge: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'slide_mountain'.split('_').map(&:capitalize).join(' '),
  slug: 'slide_mountain',
  lat: 39.319,
  lng: -119.867,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 8,
  dir_ideal: ['ENE', 'E', 'ESE'],
  dir_edge: ['NE', 'ENE', 'E', 'ESE', 'SE'])

FlySite.create(name: 'st_helena'.split('_').map(&:capitalize).join(' '),
  slug: 'st_helena',
  lat: 38.667,
  lng: -122.628,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 3,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['SW', 'WSW'],
  dir_edge: ['S', 'SSW', 'SW', 'WSW', 'W'])

FlySite.create(name: 'tollhouse'.split('_').map(&:capitalize).join(' '),
  slug: 'tollhouse',
  lat: 37.015,
  lng: -119.373,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 3,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['SW', 'WSW', 'W'],
  dir_edge: ['SSW', 'SW', 'WSW', 'W', 'WNW'])

FlySite.create(name: 'vallejo'.split('_').map(&:capitalize).join(' '),
  slug: 'vallejo',
  lat: 38.102,
  lng: -122.264,
  hourstart: 9,
  hourend: 19,
  speedmin_ideal: 7,
  speedmax_ideal: 11,
  speedmin_edge: 6,
  speedmax_edge: 14,
  dir_ideal: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'],
  dir_edge: ['N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW'])

FlySite.create(name: 'whaleback'.split('_').map(&:capitalize).join(' '),
  slug: 'whaleback',
  lat: 41.535,
  lng: -122.153,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 8,
  speedmin_edge: 0,
  speedmax_edge: 11,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['SW', 'WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'waddel'.split('_').map(&:capitalize).join(' '),
  slug: 'waddel',
  lat: 37.089,
  lng: -122.274,
  hourstart: 12,
  hourend: 18,
  speedmin_ideal: 7,
  speedmax_ideal: 9,
  speedmin_edge: 7,
  speedmax_edge: 12,
  dir_ideal: ['WSW', 'W', 'WNW'],
  dir_edge: ['WSW', 'W', 'WNW', 'NW'])

FlySite.create(name: 'windy'.split('_').map(&:capitalize).join(' '),
  slug: 'windy',
  lat: 37.364,
  lng: -122.245,
  hourstart: 10,
  hourend: 18,
  speedmin_ideal: 2,
  speedmax_ideal: 6,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['ENE', 'E'],
  dir_edge: ['NE', 'ENE', 'E', 'ESE', 'SE'])

FlySite.create(name: 'woodrat'.split('_').map(&:capitalize).join(' '),
  slug: 'woodrat',
  lat: 42.2313,
  lng: -123.0037,
  hourstart: 11,
  hourend: 18,
  speedmin_ideal: 0,
  speedmax_ideal: 7,
  speedmin_edge: 0,
  speedmax_edge: 10,
  dir_ideal: ['N', 'W', 'WNW', 'NW', 'NNW'],
  dir_edge: ['N', 'NNE', 'WSW', 'W', 'WNW', 'NW', 'NNW'])
